<?xml version="1.0"?>
<robot name="eufs"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="robot_sensors" value="${load_yaml('$(arg sensors_config_file)')}"/>
    <xacro:property name="car_settings" value="${load_yaml('$(arg car_config_file)')}"/>
    <xacro:property name="dist" value="${load_yaml('$(arg car_dimensions_file)')}"/>

    <xacro:include filename="$(find eufs_description)/urdf/vehicle/inertias.xacro"/>

    <xacro:include filename="$(find eufs_description)/urdf/vehicle/plugins.gazebo"/>

    <!-- ***************** -->
    <!-- Imported elements -->
    <!-- ***************** -->

    <!-- First we import all posible elements defined in the urdf.xacro files. All these elements are defined as macro:xacros -->

    <!-- Import Robotnik CAR base elements -->
    <xacro:arg name="publish_tf" default="false"/>
    <xacro:arg name="simulate_perception" default="false"/>
    <xacro:include filename="$(find eufs_description)/urdf/ads-dv_base.urdf.xacro">
        <xacro:arg name="publish_tf" value="$(arg publish_tf)"/>
        <xacro:arg name="simulate_perception" value="$(arg simulate_perception)"/>
    </xacro:include>

    <!-- Import all available sensors -->
    <xacro:include filename="$(find eufs_description)/sensors/all_sensors.urdf.xacro" />

    <!-- ***************** -->
    <!-- Global parameters -->
    <!-- ***************** -->

    <xacro:property name="PI" value="3.1415926535897931"/>

    <!-- Wheel parameters -->
    <xacro:property name="wheel_offset_x" value="1.0" />
    <!-- x,y,z in translation from base_link to the center of the wheel -->
    <xacro:property name="wheel_offset_y" value="0.75" />
    <xacro:property name="wheel_offset_z" value="0.0" />

    <!-- Flag to select the high or low quality model -->
    <xacro:property name="hq" value="true" />


    <!-- *************** -->
    <!-- Robots Elements -->
    <!-- *************** -->

    <!-- Here we create the robot elements using the xacro:macros imported at the beggining of this file -->

    <!-- Summit XL base -->
    <xacro:eufs_base name="eufs" publish_bf="true" hq="${hq}" />

    <!-- WHEELS -->

    <!-- hub_dia and tire_dia are the diameters of the hub and tire,
     respectively. hex_hub_depth is the distance that the hex hub is
     inset from the outer edge of the tire. It is set so that each wheel
     is a "zero offset" wheel. hex_hub_depth = tire_width / 2 -
     axle_length. -->
    <xacro:property name="hub_dia" value="0.08"/>
    <xacro:property name="tire_dia" value="0.505"/>
    <xacro:property name="tire_width" value="0.2"/>

    <xacro:property name="hex_hub_depth" value="0.120"/> <!-- or +0.072 -->
    <xacro:property name="wheel_mass" value="10.0"/>   <!-- check -->

    <!-- hex_hub_dist is the distance between left and right hex hubs when
         the shock absorbers are fully extended. axle_length is the distance
         from a U joint to the corresponding hex hub. wheel_travel is the
         vertical wheel travel. -->
    <xacro:property name="wheelbase" value="1.530"/>
    <xacro:property name="hex_hub_dist" value="1.201"/>  <!-- track/width of the car -->
    <xacro:property name="axle_length" value="0.120"/>
    <xacro:property name="wheel_travel" value="0.05"/>
    <xacro:property name="shock_z_offset" value="0.05"/>

    <!-- Degree-to-radian conversions -->
    <xacro:property name="degrees_45" value="0.785398163"/>
    <xacro:property name="degrees_90" value="1.57079633"/>
    <xacro:property name="degrees_180" value="3.14159265"/>

    <!-- shock_eff_limit is 2 * ((shock_stroke / 2) * shock_spring_constant) N. -->
    <xacro:property name="shock_eff_limit" value="50"/>
    <xacro:property name="shock_vel_limit" value="500"/>

    <xacro:property name="wheel_joint_damping" value="0.01" />
    <xacro:property name="wheel_joint_friction" value="0.1" />

    <xacro:property name="suspension_joint_damping" value="0.01" />
    <xacro:property name="suspension_joint_friction" value="0.1" />

    <!-- Wheels -->
    <xacro:macro name="left_rear_wheel">
        <joint name="rear_left_wheel_joint" type="continuous">
            <origin xyz="${-1 * wheelbase / 2}
                         ${1 * ((hex_hub_dist / 2) - axle_length)}
                         ${-wheel_travel}"
                    rpy="0 0 0"/>
            <parent link="base_footprint"/>
            <child link="left_rear_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="left_rear_wheel">
            <inertial>
                <xacro:wheels_inertia/>
            </inertial>
            <visual>
                <xacro:wheels_geometry/>
                <material name="black"/>
            </visual>
            <collision name="left_rear_wheel_collision">
                <geometry>
                    <sphere radius="0.225"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="left_rear_wheel">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="right_rear_wheel">
        <joint name="rear_right_wheel_joint" type="continuous">
            <parent link="base_footprint"/>
            <child link="right_rear_wheel"/>
            <origin xyz="${-1 * wheelbase / 2}
                         ${-1 * ((hex_hub_dist / 2) - axle_length)}
                         ${-wheel_travel}"
                    rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="right_rear_wheel">
            <inertial>
                <xacro:wheels_inertia/>
            </inertial>
            <visual>
                <xacro:wheels_geometry/>
                <material name="black"/>
            </visual>
            <collision name="right_rear_wheel_collision">
                <geometry>
                    <sphere radius="0.225"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="right_rear_wheel">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="left_front_wheel">
        <joint name="left_steering_hinge_joint" type="revolute">
            <origin xyz="${1 * wheelbase / 2}
                         ${1 * ((hex_hub_dist / 2) - axle_length)}
                         ${-wheel_travel}"
                    rpy="0 0 0"/>
            <parent link="base_footprint"/>
            <child link="left_steering_hinge"/>
            <axis xyz="0 0 1"/>
            <limit lower="-0.8727" upper="0.8727" effort="10000000" velocity="1000000"/>
        </joint>

        <link name="left_steering_hinge">
            <inertial>
                <xacro:steering_hinge_inertial_params/>
            </inertial>
            <visual>
                <xacro:steering_hinge_geometry/>
                <material name="black"/>
            </visual>
        </link>

        <joint name="front_left_wheel_joint" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <parent link="left_steering_hinge"/>
            <child link="left_front_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="left_front_wheel">
            <inertial>
                <xacro:wheels_inertia/>
            </inertial>
            <visual>
                <xacro:wheels_geometry/>
                <material name="black"/>
            </visual>
            <collision name="left_front_wheel_collision">
                <geometry>
                    <sphere radius="0.225"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="left_front_wheel">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="right_front_wheel">
        <joint name="right_steering_hinge_joint" type="revolute">
            <parent link="base_footprint"/>
            <child link="right_steering_hinge"/>
            <axis xyz="0 0 1"/>
            <origin xyz="${1 * wheelbase / 2}
                         ${-1 * ((hex_hub_dist / 2) - axle_length)}
                         ${-wheel_travel}"
                    rpy="0 0 0"/>
            <limit lower="-0.8727" upper="0.8727" effort="10000000" velocity="1000000"/>
        </joint>

        <link name="right_steering_hinge">
            <inertial>
                <xacro:steering_hinge_inertial_params/>
            </inertial>
            <visual>
                <xacro:steering_hinge_geometry/>
            </visual>
        </link>

        <joint name="front_right_wheel_joint" type="continuous">
            <origin xyz="0 0 0"
                    rpy="0 0 0"/>
            <parent link="right_steering_hinge"/>
            <child link="right_front_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>
        <link name="right_front_wheel">
            <inertial>
                <xacro:wheels_inertia/>
            </inertial>
            <visual>
                <xacro:wheels_geometry/>
                <material name="black"/>
            </visual>
            <collision name="right_front_wheel_collision">
                <geometry>
                    <sphere radius="0.225"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="right_front_wheel">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <!-- ################################################################## -->
    <!-- #### Add the left rear wheel with its joints and tranmissions #### -->
    <!-- ################################################################## -->
    <xacro:left_rear_wheel/>

    <!-- ################################################################### -->
    <!-- #### Add the right rear wheel with its joints and tranmissions #### -->
    <!-- ################################################################### -->
    <xacro:right_rear_wheel/>

    <!-- ############################################################################## -->
    <!-- #### Add the left front wheel with its joints, steering and tranmissions #### -->
    <!-- ############################################################################## -->
    <xacro:left_front_wheel/>

    <!-- ############################################################################## -->
    <!-- #### Add the right front wheel with its joints, steering and tranmissions #### -->
    <!-- ############################################################################## -->
    <xacro:right_front_wheel/>

    <!-- *********************************************** -->
    <!--                 MAIN SENSORS                    -->
    <!-- *********************************************** -->

    <!--     LOCATIONS: (XYZ)
    IMU: 0.0 0.0 0.170
    GPS: -0.110 0.0 0.9
    LIDAR: 1.700 0.0 -0.150
    STEREO CAM: -0.110 0.0 0.800 -->

    <xacro:sensor_imu parent="base_footprint" prefix="imu">
        <origin xyz="-0.0 0.0 0.0" rpy="0 0 0"/>
    </xacro:sensor_imu>

    <xacro:sensor_gps parent="base_footprint" prefix="gps">
        <origin xyz="0.0 0.0 0.4" rpy="0 0 0"/>
    </xacro:sensor_gps>

    <!-- Simulate raw perception sensors only if we're not using the abstracted perception simulation -->
    <xacro:unless value="$(arg simulate_perception)">
        <xacro:VLP-16R parent="base_footprint" name="velodyne" topic="/velodyne_points" hz="10" samples="800">
            <origin xyz="1.58 0.0 -0.1" rpy="0 ${1*M_PI/180.0} 0"/>
        </xacro:VLP-16R>

        <xacro:zed_camera parent="base_footprint" prefix="zed">
            <origin xyz="0.1 0.0 0.52" rpy="0 0 0"/>
        </xacro:zed_camera>
    </xacro:unless>


    <!-- *********************************************** -->
    <!-- EXTRA SENSORS FROM THE ROBOTNIK SENSORS LIBRARY -->
    <!-- *********************************************** -->

    <!--     <xacro:sensor_hokuyo_utm30lx parent="base_link" prefix="lidar">
        <origin xyz="1.700 0.0 -0.080" rpy="0 -0.0174533 0"/>
    </xacro:sensor_hokuyo_utm30lx>

    <xacro:sensor_hokuyo3d name="hokuyo3d" parent="base_link">
        <origin xyz="0.9 0.0 0.450" rpy="0 0.35 0"/>
    </xacro:sensor_hokuyo3d>


    <xacro:sensor_hokuyo_urg04lx name="hokuyo1" parent="base_link">
        <origin xyz="-0.1 0.0 0.33" rpy="0 0 0"/>
    </xacro:sensor_hokuyo_urg04lx>


    <xacro:sensor_axis name="camera" parent="base_link">
        <origin xyz="0.19 0 0.17" rpy="0 ${15*PI/180} 0"/>
    </xacro:sensor_axis>


    <xacro:sensor_asus_xtion_pro name="xtion_pro" parent="base_link">
        <origin xyz="0.3 0.0 0.3" rpy="0 0 0"/>
    </xacro:sensor_asus_xtion_pro>


    <xacro:sensor_kinect parent="base_link" prefix="kinect">
        <origin xyz="0.0 0.0 0.45" rpy="0 0 0"/>
    </xacro:sensor_kinect>

    <xacro:BB2-08S2C-60 prefix="bee" frame="bee" name="bee"/>

    <xacro:sensor_fotonic name="fotonic" parent="base_link">
        <origin xyz="0.3 0.0 0.24" rpy="0 0 0"/>
    </xacro:sensor_fotonic>   -->

</robot>
