<?xml version="1.0"?>
<robot name="eufs" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="publish_tf" default="false"/>
  <xacro:arg name="simulate_perception" default="false"/>

  <xacro:include filename="$(find eufs_description)/urdf/eufs_base.gazebo.xacro">
    <xacro:arg name="publish_tf" value="$(arg publish_tf)"/>
    <xacro:arg name="simulate_perception" value="$(arg simulate_perception)"/>
  </xacro:include>

  <xacro:macro name="eufs_base" params="name publish_bf hq">

    <!-- Robot mechanical and motor parameters -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="wheel_width" value="0.175" />
  <!--   <xacro:property name="clearance" value="${tire_diameter/2.0}" />-->
    <xacro:property name="clearance" value="0.0" />

    <!--  These are for the position of the center of mass  -->
    <xacro:property name="base_mass" value="140"/>

    <!-- BASE FOOTPRINT -->
    <link name="base_footprint"/>

    <joint name="chassis_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="chassis"/>
      <origin xyz="0 0 ${clearance}"
              rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="chassis">
      <visual>
        <origin xyz="0 0 ${clearance}" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://eufs_description/meshes/ads-dv.dae"/>
        </geometry>
      </visual>
      <inertial>
        <origin xyz="0 0 ${clearance}" rpy="0 0 0" />
        <mass value="${base_mass}" />
        <inertia
            ixx="16.3"
            ixy="0"
            ixz="0"
            iyy="33.6"
            iyz="0"
            izz="47.9" />
      </inertial>
      <collision>
        <origin xyz="0 0 ${clearance}" rpy="0 0 0" />  <!-- height is the clearance -->
        <geometry>
          <mesh filename="package://eufs_description/meshes/ads-dv.dae"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>
</robot>
