<?xml version="1.0"?>
<robot name="wheels" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="tire_diameter" value="0.505"/>
  <xacro:property name="tire_width" value="0.2"/>

  <xacro:property name="wheel_mass" value="10.0"/>   <!-- check -->

  <xacro:property name="degrees_90" value="1.5708"/>

  <xacro:property name="wheelbase" value="1.530"/>
  <xacro:property name="hex_hub_dist" value="1.201"/>  <!-- track/width of the car -->
  <xacro:property name="axle_length" value="0.120"/>
  <xacro:property name="wheel_travel" value="0.05"/>

  <!-- Description of the wheel itself -->
  <xacro:macro name="wheel"
               params="lr_prefix fr_prefix">
    <link name="${lr_prefix}_${fr_prefix}_wheel">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${wheel_mass}"/>
        <inertia
            ixx="0.3"
            ixy="0"
            ixz="0"
            iyy="0.2"
            iyz="0"
            izz="0.2"   />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <mesh filename="package://eufs_description/meshes/wheel_${lr_prefix}.dae"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${tire_diameter / 2}" length="${tire_width}"/>
        </geometry>
      </collision>
    </link>

    <gazebo reference="${lr_prefix}_${fr_prefix}_wheel">
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>

  <!-- Description of how a front wheel is connected to the base_footprint -->
  <xacro:macro name="front_wheel"
               params="lr_prefix lr_reflect">

    <joint name="${lr_prefix}_steering_hinge_joint" type="revolute">
      <origin xyz="${1 * wheelbase / 2}
                   ${lr_reflect * ((hex_hub_dist / 2) - axle_length)}
                   ${-wheel_travel}"
              rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="${lr_prefix}_steering_hinge"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.8727" upper="0.8727" effort="10000000" velocity="1000000"/>
    </joint>

    <link name="${lr_prefix}_steering_hinge">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1" />
        <inertia
            ixx="0.004"
            ixy="0"
            ixz="0"
            iyy="0.004"
            iyz="0"
            izz="0.004"   />
      </inertial>
    </link>

    <joint name="front_${lr_prefix}_wheel_joint" type="continuous">
      <origin xyz="0 0 0"
              rpy="0 0 0"/>
      <parent link="${lr_prefix}_steering_hinge"/>
      <child link="${lr_prefix}_front_wheel"/>
      <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="front"/>
  </xacro:macro>

  <!-- Description of how a rear wheel is connected to the base_footprint -->
  <xacro:macro name="rear_wheel"
               params="lr_prefix lr_reflect">

    <joint name="rear_${lr_prefix}_wheel_joint" type="continuous">
      <origin xyz="${-1 * wheelbase / 2}
                   ${lr_reflect * ((hex_hub_dist / 2) - axle_length)}
                   ${-wheel_travel}"
              rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="${lr_prefix}_rear_wheel"/>
      <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="rear"/>
  </xacro:macro>

</robot>
