<?xml version="1.0"?>
<robot name="wheels" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="degrees_90" value="1.5708"/>

  <!-- Description of the wheel itself -->
  <xacro:macro name="wheel"
               params="lr_prefix fr_prefix">
    <link name="${lr_prefix}_${fr_prefix}_wheel">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${config['wheel']['mass']}"/>
        <inertia
            ixx="${config['wheel']['inertia']['ixx']}"
            ixy="${config['wheel']['inertia']['ixy']}"
            ixz="${config['wheel']['inertia']['ixz']}"
            iyy="${config['wheel']['inertia']['iyy']}"
            iyz="${config['wheel']['inertia']['iyz']}"
            izz="${config['wheel']['inertia']['izz']}"   />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <mesh filename="package://eufs_description/meshes/wheel_${lr_prefix}.dae"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${config['wheel']['diameter'] / 2}" length="${config['wheel']['width']}"/>
        </geometry>
      </collision>
    </link>

    <gazebo reference="${lr_prefix}_${fr_prefix}_wheel">
      <material>Gazebo/Black</material>
      <mu1>${config['wheel']['friction']}</mu1>
      <mu2>${config['wheel']['friction']}</mu2>
      <!-- <minDepth>0.005</minDepth> -->
      <kp>${config['wheel']['kp']}</kp>
    </gazebo>
  </xacro:macro>

  <!-- Description of how a front wheel is connected to the base_footprint -->
  <xacro:macro name="front_wheel"
               params="lr_prefix lr_reflect">

    <joint name="${lr_prefix}_steering_hinge_joint" type="revolute">
      <origin xyz="${1 * config['wheel']['wheelbase'] / 2}
                   ${lr_reflect * ((config['wheel']['hex_hub_dist'] / 2) - config['wheel']['axle_length'])}
                   ${-config['wheel']['wheel_travel']}"
              rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="${lr_prefix}_steering_hinge"/>
      <axis xyz="0 0 1"/>
      <limit lower="${config['wheel']['wheelbase'] * -1}" upper="${config['wheel']['wheelbase']}" effort="10000000" velocity="1000000"/>
    </joint>

    <link name="${lr_prefix}_steering_hinge">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${config['steering_hinge']['mass']}"/>
        <inertia
            ixx="${config['steering_hinge']['inertia']['ixx']}"
            ixy="${config['steering_hinge']['inertia']['ixy']}"
            ixz="${config['steering_hinge']['inertia']['ixz']}"
            iyy="${config['steering_hinge']['inertia']['iyy']}"
            iyz="${config['steering_hinge']['inertia']['iyz']}"
            izz="${config['steering_hinge']['inertia']['izz']}"   />
      </inertial>
    </link>

    <joint name="front_${lr_prefix}_wheel_joint" type="continuous">
      <origin xyz="0 0 0"
              rpy="0 0 0"/>
      <parent link="${lr_prefix}_steering_hinge"/>
      <child link="${lr_prefix}_front_wheel"/>
      <axis xyz="0 1 0"/>
      <limit lower="0" upper="0" effort="10000000" velocity="1000000"/>
    </joint>

    <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="front"/>
  </xacro:macro>

  <!-- Description of how a rear wheel is connected to the base_footprint -->
  <xacro:macro name="rear_wheel"
               params="lr_prefix lr_reflect">

    <joint name="rear_${lr_prefix}_wheel_joint" type="continuous">
      <origin xyz="${-1 * config['wheel']['wheelbase'] / 2}
                   ${lr_reflect * ((config['wheel']['hex_hub_dist'] / 2) - config['wheel']['axle_length'])}
                   ${-config['wheel']['wheel_travel']}"
              rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="${lr_prefix}_rear_wheel"/>
      <axis xyz="0 1 0"/>
      <limit lower="0" upper="0" effort="10000000" velocity="1000000"/>
    </joint>

    <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="rear"/>
  </xacro:macro>

</robot>
