# Probabilities for swapping cone colours are stored in the following format
# ground_truth_colour:
#   new_colour: <probability of switch from ground_truth_colour to new_colour>
# Ensure probabilities sum to 1.0

blue:
  blue: 0.9
  yellow: 0.08
  orange: 0.01
  big_orange: 0.01

yellow:
  blue: 0.08
  yellow: 0.9
  orange: 0.01
  big_orange: 0.01

orange:
  blue: 0.05
  yellow: 0.05
  orange: 0.8
  big_orange: 0.1

big_orange:
  blue: 0.01
  yellow: 0.01
  orange: 0.28
  big_orange: 0.7