blueMismatch: 0.1
blueToYellow: 0.2
blueToOrange: 0.2
blueToBigOrange: 0.2
blueToUnknown: 0.2
blueToVoid: 0.2

yellowMismatch: 0.1
yellowToBlue: 0.2
yellowToOrange: 0.2
yellowToBigOrange: 0.2
yellowToUnknown: 0.2
yellowToVoid: 0.2

orangeMismatch: 0.1
orangeToYellow: 0.2
orangeToBlue: 0.2
orangeToBigOrange: 0.2
orangeToUnknown: 0.2
orangeToVoid: 0.2

bigOrangeMismatch: 0.1
bigOrangeToYellow: 0.2
bigOrangeToOrange: 0.2
bigOrangeToBlue: 0.2
bigOrangeToUnknown: 0.2
bigOrangeToVoid: 0.2

unknownMismatch: 0.1
unknownToYellow: 0.2
unknownToOrange: 0.2
unknownToBigOrange: 0.2
unknownToBlue: 0.2
unknownToVoid: 0.2
