inertia:
  m:        190.0   # Weight of the Vehicle [kg]
  g:        9.81    # Graviti force         [m/s^2]
  I_z:      110    # Inertial force I_zz

kinematics:
  l: 1.53           # Vehicle Length [m]
  b_F: 1.22          # From COG to front axle [m]
  b_R: 1.22         # From COG to rear axle [m]
  w_front: 0.5    # Percentage of weight front

tire:
  tire_coefficient: 1.0
  B: 12.56
  C: -1.38
  D: 1.60
  E: -0.58
  radius: 0.2525

aero:
  C_Down: # F_Downforce = C_Downforce*v_x^2; C_Downforce = a*b*c
    a: 1.22
    b: 2.6
    c: 0.6
  C_drag: # F_Drag = C_Drag*v_x^2; C_drag = a*b*c
    a: 0.7
    b: 1.0
    c: 1.0

wheel:
  max_steering: 0.8727
  diameter: 0.505
  width: 0.2
  mass: 10.0
  inertia:
    ixx: 0.3
    ixy: 0
    ixz: 0
    iyy: 0.2
    iyz: 0
    izz: 0.2
  wheelbase: 1.530
  hex_hub_dist: 1.201
  axle_length: 0.120
  wheel_travel: 0.05
  friction: 2
  kp: 1e8

steering_hinge:
  mass: 1
  inertia:
    ixx: 0.04
    ixy: 0
    ixz: 0
    iyy: 0.04
    iyz: 0
    izz: 0.04

drivetrain:
  Cm1: 5000
  Cr0: 180
  inertia: 0.4 # wheel_plus_packaging
  r_dyn: 0.231
  nm_wheels: 4

torque_vectoring:
  K_FFW: 2.1
  K_p: 500
  shrinkage: 0.8
  K_stability: 0.004
