wheel:
  max_steering: 0.8727
  diameter: 0.505
  width: 0.2
  mass: 10.0
  inertia:
    ixx: 0.3
    ixy: 0
    ixz: 0
    iyy: 0.2
    iyz: 0
    izz: 0.2
  wheelbase: 1.530
  hex_hub_dist: 1.201
  axle_length: 0.120
  wheel_travel: 0.05

steering_hinge:
  mass: 1
  inertia:
    ixx: 0.04
    ixy: 0
    ixz: 0
    iyy: 0.04
    iyz: 0
    izz: 0.04
